Repository frc1937/2025ReefscapeCode, pull requests merged in 2025-01, with the labels that each got.

#4 Added support for more key inputs and a keyboard-to-NetworkTables logger.
  src/main/java/frc/lib/generic/hardware/KeyboardController.java
  src/main/python/keyboard_to_nt.py
Labels: enhancement

#7 Fixed follower tomfoolery
  build.gradle
  src/main/java/frc/lib/generic/hardware/motor/Motor.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/ctre/GenericTalonFX.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/ctre/GenericTalonSRX.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/rev/GenericSparkBase.java
Labels: bug, requires real robot

#12 Improved autonomous following
  src/main/deploy/pathplanner/settings.json
  src/main/java/frc/lib/generic/hardware/HardwareManager.java
  src/main/java/frc/lib/util/LocalADStarAK.java
  src/main/java/frc/lib/util/LoggedTunableNumber.java
  src/main/java/frc/lib/util/flippable/Flippable.java
  src/main/java/frc/lib/util/flippable/FlippablePose2d.java
  src/main/java/frc/lib/util/flippable/FlippableRotation2d.java
  src/main/java/frc/lib/util/flippable/FlippableTranslation2d.java
  src/main/java/frc/lib/util/flippable/FlippableTranslation3d.java
  src/main/java/frc/lib/util/mirrorable/Mirrorable.java
  src/main/java/frc/lib/util/mirrorable/MirrorablePose2d.java
  src/main/java/frc/lib/util/mirrorable/MirrorableRotation2d.java
  src/main/java/frc/lib/util/mirrorable/MirrorableTranslation3d.java
  src/main/java/frc/robot/GlobalConstants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/PathfindToFeeder.java
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimator5990.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModuleConstants.java
  src/main/java/frc/robot/utilities/FieldLocations.java
  src/main/java/frc/robot/utilities/PathPlannerConstants.java
Labels: enhancement

#14 Ports class
  simgui-ds.json
  src/main/java/frc/robot/subsystems/leds/Leds.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModuleConstants.java
  src/main/java/frc/robot/utilities/PortsConstants.java
Labels: enhancement

#21 Added a coral intake
  src/main/java/frc/robot/subsystems/coralIntake/CoralIntake.java
  src/main/java/frc/robot/subsystems/coralIntake/CoralIntakeConstants.java
  src/main/java/frc/robot/utilities/PortsConstants.java
Labels: feature

#17 Added Pathfinding to the closest feeder based on alliance
  src/main/deploy/pathplanner/autos/New Auto.auto
  src/main/deploy/pathplanner/paths/nextToBottomFeeder.path
  src/main/deploy/pathplanner/paths/nextToTopFeeder.path
  src/main/java/frc/lib/util/flippable/Flippable.java
  src/main/java/frc/lib/util/flippable/FlippablePose2d.java
  src/main/java/frc/robot/GlobalConstants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/PathfindingCommands.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommands.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/utilities/FieldConstants.java
  src/main/java/frc/robot/utilities/FieldLocations.java
  src/main/java/frc/robot/utilities/PathPlannerConstants.java
Labels: requires sim testing, enhancement

#26 Elevator subsystem
  README.md
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/elevator/Elevator.java
  src/main/java/frc/robot/subsystems/elevator/ElevatorConstants.java
  src/main/java/frc/robot/utilities/PortsConstants.java
Labels: feature, requires sim testing

#34 Added a command that pathfinds to the closest side of reef to the robot
  src/main/java/frc/lib/util/flippable/FlippablePose2d.java
  src/main/java/frc/robot/commands/PathfindingCommands.java
  src/main/java/frc/robot/utilities/FieldConstants.java
Labels: feature

#8 LED position indicator
  src/main/java/frc/lib/util/CustomLEDPatterns.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/leds/Leds.java
Labels: feature, requires real robot
