Repository frc1937/2025ReefscapeCode, pull requests merged in 2025-02, with the labels that each got.

#45 Robot Control
  simgui-ds.json
  src/main/java/frc/lib/generic/Feedforward.java
  src/main/java/frc/lib/generic/GenericSubsystem.java
  src/main/java/frc/lib/generic/GenericValue.java
  src/main/java/frc/lib/generic/OdometryThread.java
  src/main/java/frc/lib/generic/PID.java
  src/main/java/frc/lib/generic/hardware/HardwareManager.java
  src/main/java/frc/lib/generic/hardware/encoder/Encoder.java
  src/main/java/frc/lib/generic/hardware/encoder/EncoderConfiguration.java
  src/main/java/frc/lib/generic/hardware/encoder/EncoderProperties.java
  src/main/java/frc/lib/generic/hardware/encoder/EncoderSignal.java
  src/main/java/frc/lib/generic/hardware/encoder/hardware/GenericCanCoder.java
  src/main/java/frc/lib/generic/hardware/motor/Motor.java
  src/main/java/frc/lib/generic/hardware/motor/MotorFactory.java
  src/main/java/frc/lib/generic/hardware/motor/MotorProperties.java
  src/main/java/frc/lib/generic/hardware/motor/MotorSignal.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/MotorUtilities.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/rev/GenericSparkMax.java
  src/main/java/frc/lib/generic/hardware/pigeon/PigeonSignal.java
  src/main/java/frc/lib/generic/hardware/sensors/Sensor.java
  src/main/java/frc/lib/generic/hardware/sensors/hardware/DigitalInput.java
  src/main/java/frc/lib/generic/simulation/SimulationProperties.java
  src/main/java/frc/lib/math/Conversions.java
  src/main/java/frc/lib/math/Optimizations.java
  src/main/java/frc/lib/util/Controller.java
  src/main/java/frc/lib/util/CustomLEDPatterns.java
  src/main/java/frc/lib/util/flippable/Flippable.java
  src/main/java/frc/robot/ButtonControls.java
  src/main/java/frc/robot/GlobalConstants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/commands/AlgaeManipulationCommands.java
  src/main/java/frc/robot/commands/ClimbingCommands.java
  src/main/java/frc/robot/commands/PathfindingCommands.java
  src/main/java/frc/robot/poseestimation/photoncamera/VisionConstants.java
  src/main/java/frc/robot/subsystems/algaeblaster/AlgaeBlaster.java
  src/main/java/frc/robot/subsystems/algaeblaster/AlgaeBlasterConstants.java
  src/main/java/frc/robot/subsystems/algaeintake/AlgaeIntake.java
  src/main/java/frc/robot/subsystems/algaeintake/AlgaeIntakeConstants.java
  src/main/java/frc/robot/subsystems/coralintake/CoralIntake.java
  src/main/java/frc/robot/subsystems/elevator/Elevator.java
  src/main/java/frc/robot/subsystems/leds/Leds.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModuleConstants.java
  src/main/java/frc/robot/utilities/PathPlannerConstants.java
  src/main/java/frc/robot/utilities/PortsConstants.java
  src/test/java/frc/robot/ButtonTest.java
Labels: feature, enhancement

#49 Software limits
  src/main/java/frc/lib/generic/hardware/motor/MotorConfiguration.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/ctre/GenericTalonFX.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/rev/GenericSparkBase.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/simulated/SimulatedTalonMotor.java
  src/main/java/frc/robot/subsystems/algaeblaster/AlgaeBlasterConstants.java
  src/main/java/frc/robot/subsystems/algaeintake/AlgaeIntakeConstants.java
  src/main/java/frc/robot/subsystems/elevator/Elevator.java
  src/main/java/frc/robot/subsystems/elevator/ElevatorConstants.java
Labels: bug, enhancement

#53 FIX SWERVE BUG
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
Labels: bug

#51 A questionnaire that lets the drive control what happens during the autonomous
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/CoralManipulationCommands.java
  src/main/java/frc/robot/commands/PathfindingCommands.java
  src/main/java/frc/robot/commands/autocommands/Questionnaire.java
  src/main/java/frc/robot/subsystems/algaeblaster/AlgaeBlaster.java
  src/main/java/frc/robot/subsystems/elevator/Elevator.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/utilities/FieldConstants.java
Labels: feature, requires sim testing, enhancement

#56 Cleaned up a bunch of code, fixed CAD in sim and tuned a bit.
  src/main/java/frc/robot/ButtonControls.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/AlgaeManipulationCommands.java
  src/main/java/frc/robot/commands/PathfindingCommands.java
  src/main/java/frc/robot/commands/autocommands/Questionnaire.java
  src/main/java/frc/robot/subsystems/algaeblaster/AlgaeBlaster.java
  src/main/java/frc/robot/subsystems/algaeblaster/AlgaeBlasterConstants.java
  src/main/java/frc/robot/subsystems/algaeintake/AlgaeIntake.java
  src/main/java/frc/robot/subsystems/algaeintake/AlgaeIntakeConstants.java
  src/main/java/frc/robot/subsystems/elevator/Elevator.java
  src/main/java/frc/robot/subsystems/elevator/ElevatorConstants.java
  src/main/java/frc/robot/subsystems/leds/Leds.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/utilities/FieldConstants.java
Labels: enhancement

#59 Bug Fixes
  build.gradle
  src/main/deploy/pathplanner/navgrid.json
  src/main/deploy/pathplanner/settings.json
  src/main/java/frc/lib/generic/ProfiledPID.java
  src/main/java/frc/lib/generic/hardware/controllers/Controller.java
  src/main/java/frc/lib/generic/hardware/controllers/KeyboardController.java
  src/main/java/frc/lib/util/flippable/FlippableUtils.java
  src/main/java/frc/robot/ButtonControls.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/AlgaeManipulationCommands.java
  src/main/java/frc/robot/commands/ClimbingCommands.java
  src/main/java/frc/robot/commands/CoralManipulationCommands.java
  src/main/java/frc/robot/commands/PathfindingCommands.java
  src/main/java/frc/robot/commands/autocommands/Questionnaire.java
  src/main/java/frc/robot/commands/pathfinding/PathfindingCommands.java
  src/main/java/frc/robot/commands/pathfinding/PathfindingConstants.java
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimator.java
  src/main/java/frc/robot/poseestimation/poseestimator/PoseEstimatorConstants.java
  src/main/java/frc/robot/subsystems/algaeblaster/AlgaeBlaster.java
  src/main/java/frc/robot/subsystems/coralintake/CoralIntake.java
  src/main/java/frc/robot/subsystems/elevator/Elevator.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/subsystems/swerve/SwerveCommands.java
  src/main/java/frc/robot/subsystems/swerve/SwerveConstants.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModule.java
  src/main/java/frc/robot/subsystems/swerve/SwerveModuleConstants.java
  src/main/java/frc/robot/utilities/FieldConstants.java
  src/main/java/frc/robot/utilities/PathPlannerConstants.java
  src/main/python/keyboard_to_nt.py
  src/test/elastic-layout.json
  src/test/java/frc/robot/ButtonTest.java
  vendordeps/PathplannerLib-2025.2.3.json
  vendordeps/Phoenix6-25.2.2.json
  vendordeps/REVLib-2025.0.2.json
Labels: bug, feature, requires sim testing, enhancement, optimization

#60 Optimizations
  src/main/java/frc/lib/generic/hardware/HardwareManager.java
  src/main/java/frc/lib/generic/hardware/encoder/hardware/GenericCanCoder.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/ctre/GenericTalonFX.java
  src/main/java/frc/lib/generic/hardware/motor/hardware/simulated/SimulatedTalonMotor.java
  src/main/java/frc/lib/generic/hardware/pigeon/hardware/GenericPigeon2.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/swerve/Swerve.java
  src/main/java/frc/robot/utilities/PathPlannerConstants.java
Labels: enhancement, optimization
